name: AppService Linux Container C# Workflow

on: 
  workflow_dispatch:
#   push:
#     branches: main
#     paths:
#     - 'dncapp/**'

env:
  ACR_LOGIN_SERVER: jfvacr.azurecr.io  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: jfvacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        cd dncapp
        docker build . -t jfvacr.azurecr.io/dncapp:${{ github.sha }}
        docker push jfvacr.azurecr.io/dncapp:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        # app-name: 'myapp'
        publish-profile: ${{ secrets.WEBAPPC2A }}
        images: 'jfvacr.azurecr.io/dncapp:${{ github.sha }}'
