name: AppService Linux Container C# Workflow

on: 
  workflow_dispatch:
#   push:
#     branches: main
#     paths:
#     - 'dncapp/**'

env:
  ACR_LOGIN_SERVER: jfvacr.azurecr.io  
  APP_NAME: dncapp
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}        
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        cd dncapp
        docker build . -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        # app-name: 'myapp'
        publish-profile: ${{ secrets.WEBAPPC2A }}
        images: '${{ env.ACR_LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}'
