name: Close Tim's Issue

on: 
  workflow_dispatch:
     inputs:
      TimIssue:
        default: "my input value"


env:
  ISSUE_TO_CLOSE: 2  
  HELLO_WORLD: 'Hello World'
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.6.0
      
    - name: Show Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
    - name: hello world var
      run: echo $HELLO_WORLD
