name: Close Tim's Issue

on: 
  workflow_dispatch:
     inputs:
      TimIssue:
        description: "which issue shall we close?"
        default: "my input value"


env:
  ISSUE_TO_CLOSE: 2  
  HELLO_WORLD: 'Hello World'
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.6.0
      
    - name: Show Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
      
    - name: hello input
      run: echo ${{ inputs.TimIssue }} 
      
    - name: hello world var
      run: echo $HELLO_WORLD
    
    - name: Close Issue
      uses: peter-evans/close-issue@v2
      with:
          issue-number: ${{ inputs.TimIssue }} 
          comment: Auto-closing issue
          close-reason: "Tim said so!"
