name: Context testing

on:  
  workflow_dispatch:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    
       
    
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub sha        
        run: echo '${{ github.sha }}'
      - name: Run Cut cmd on SHA
        run: echo "Cut_SHA=`echo ${GITHUB_SHA} | cut -c 1-7`" >> $GITHUB_ENV          
      - name: Run Cut cmd on SHA
        run: echo "Cut SHA is ${{ env.Cut_SHA }}"          
      - name: Concat 2 vars
        run: echo "ConcatVar=`${{ env.Cut_SHA }}boo${GITHUB_SHA}`" >> $GITHUB_ENV  
      - name: Print Concat 2 vars
        run: echo "ConcatVar is ${{ env.ConcatVar }}"          
      - name: Tim Test  
        run: echo "Cut SHA is "env.Cut_SHA
      - name: Get Rev-Parse
        run: echo "Rev_Parse=`git rev-parse --short HEAD`" >> $GITHUB_ENV  
      - name: Print Rev_Parse
        run: echo "Rev_Parse is ${{ env.Rev_Parse }}"  
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
